package com.santarest;


import com.google.gson.reflect.TypeToken;
import com.santarest.annotations.Body;
import com.santarest.annotations.Field;
import com.santarest.annotations.Part;
import com.santarest.annotations.Path;
import com.santarest.annotations.Query;
import com.santarest.annotations.RequestHeader;
import com.santarest.annotations.ResponseHeader;
import com.santarest.annotations.RestAction;
import com.santarest.annotations.Status;
import com.santarest.converter.Converter;
import com.santarest.http.ByteArrayBody;
import com.santarest.http.FileBody;
import com.santarest.http.Header;
import com.santarest.http.HttpBody;
import com.santarest.http.Response;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.MethodSpec;
import com.squareup.javapoet.ParameterizedTypeName;
import com.squareup.javapoet.TypeName;
import com.squareup.javapoet.TypeSpec;

import org.apache.commons.lang.StringUtils;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;

import javax.annotation.processing.Filer;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;

import static com.santarest.TypeUtils.equalTypes;

public class HelpersGenerator extends Generator {
    static final String HELPER_SUFFIX = "Helper";
    private static final String BASE_HEADERS_MAP = "headers";

    public HelpersGenerator(Filer filer) {
        super(filer);
    }

    @Override
    public void generate(ArrayList<RestActionClass> actionClasses) {
        for (RestActionClass restActionClass : actionClasses) {
            generate(restActionClass);
        }
    }

    private void generate(RestActionClass actionClass) {
        TypeSpec.Builder classBuilder = TypeSpec.classBuilder(actionClass.getHelperName())
                .addModifiers(Modifier.PUBLIC)
                .addJavadoc("SantaRest compile time, autogenerated class, which fills actions")
                .addSuperinterface(ParameterizedTypeName.get(ClassName.get(SantaRest.ActionHelper.class), actionClass.getTypeName()));

        classBuilder.addMethod(createFillRequestMethod(actionClass));
        classBuilder.addMethod(createOnResponseMethod(actionClass));
        saveClass(actionClass.getPackageName(), classBuilder.build());
    }

    private MethodSpec createFillRequestMethod(RestActionClass actionClass) {
        MethodSpec.Builder builder = MethodSpec.methodBuilder("fillRequest")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(RequestBuilder.class)
                .addParameter(RequestBuilder.class, "requestBuilder")
                .addParameter(TypeName.get(actionClass.getTypeElement().asType()), "action")
                .addStatement("requestBuilder.setMethod($T.$L)", RestAction.Method.class, actionClass.getMethod())
                .addStatement("requestBuilder.setRequestType($T.$L)", RestAction.Type.class, actionClass.getRequestType())
                .addStatement("requestBuilder.setPath($S)", actionClass.getPath());
        addPathParams(actionClass, builder);
        addParts(actionClass, builder);
        addRequestHeaders(actionClass, builder);
        addRequestFields(actionClass, builder);
        addRequestQueries(actionClass, builder);
        addRequestBody(actionClass, builder);
        builder.addStatement("return requestBuilder");
        return builder.build();
    }

    //TODO: replace logic like in retrofit
    private void addRequestFields(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(Field.class)) {
            Field annotation = element.getAnnotation(Field.class);
            builder.beginControlFlow("if (action.$L != null)", element);
            builder.addStatement("requestBuilder.addField($S, action.$L.toString())", annotation.value(), element);
            builder.endControlFlow();
        }
    }

    private void addRequestQueries(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(Query.class)) {
            Query annotation = element.getAnnotation(Query.class);
            if (TypeUtils.isPrimitive(element)) {
                builder.addStatement("requestBuilder.addQueryParam($S, $T.valueOf(action.$L), $L, $L)", annotation.value(), String.class, element, annotation.encodeName(), annotation.encodeValue());
            } else {
                builder.beginControlFlow("if (action.$L != null)", element);
                builder.addStatement("requestBuilder.addQueryParam($S, action.$L.toString(), $L, $L)", annotation.value(), element, annotation.encodeName(), annotation.encodeValue());
                builder.endControlFlow();
            }
        }
    }

    private void addRequestBody(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(Body.class)) {
            builder.addStatement("requestBuilder.setBody(action.$L)", element);
            break;
        }
    }

    private void addRequestHeaders(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(RequestHeader.class)) {
            RequestHeader annotation = element.getAnnotation(RequestHeader.class);
            builder.beginControlFlow("if (action.$L != null)", element);
            builder.addStatement("requestBuilder.addHeader($S, action.$L.toString())", annotation.value(), element);
            builder.endControlFlow();
        }
    }

    private void addPathParams(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(Path.class)) {
            Path param = element.getAnnotation(Path.class);
            String path = param.value();
            String name = element.getSimpleName().toString();
            if (StringUtils.isEmpty(path)) {
                path = name;
            }
            boolean encode = param.encode();
            builder.beginControlFlow("if (action.$L != null)", name);
            builder.addStatement("requestBuilder.addPathParam($S, action.$L.toString(), $L)", path, name, encode);
            builder.endControlFlow();
        }
    }

    private void addParts(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(Part.class)) {
            Part part = element.getAnnotation(Part.class);
            String partName = part.value();
            String name = element.getSimpleName().toString();
            if (StringUtils.isEmpty(partName)) {
                partName = name;
            }
            String encode = part.encoding();
            String httpBodyName = "httpBody";
            builder.beginControlFlow("if (action.$L != null)", name);
            if (TypeUtils.equalTypes(element, File.class)) {
                builder.addStatement("$T $L = new $T($S, action.$L)", HttpBody.class,httpBodyName, FileBody.class, encode, name);
            } else if (TypeUtils.equalTypes(element, byte[].class)) {
                builder.addStatement("$T $L = new $T($S, action.$L)", HttpBody.class,httpBodyName, ByteArrayBody.class, encode, name);
            } else if (TypeUtils.equalTypes(element, String.class)) {
                builder.addStatement("$T $L = new $T($S, action.$L.getBytes())",HttpBody.class, httpBodyName, ByteArrayBody.class, encode, name);
            } else {
                builder.addStatement("$T $L = action.$L", HttpBody.class,httpBodyName, name);
            }
            builder.addStatement("requestBuilder.addPart($S, $L, $S)", partName, httpBodyName, encode);
            builder.endControlFlow();
        }
    }

    private MethodSpec createOnResponseMethod(RestActionClass actionClass) {
        MethodSpec.Builder builder = MethodSpec.methodBuilder("onResponse")
                .addModifiers(Modifier.PUBLIC)
                .addAnnotation(Override.class)
                .returns(ClassName.get(actionClass.getTypeElement().asType()))
                .addParameter(actionClass.getTypeName(), "action")
                .addParameter(Response.class, "response")
                .addParameter(Converter.class, "converter");

        addStatusField(actionClass, builder);
        addResponses(actionClass, builder);
        addBasicHeadersMap(actionClass, builder);
        addResponseHeaders(actionClass, builder);
        builder.addStatement("return action");
        return builder.build();
    }

    private void addResponses(RestActionClass actionClass, MethodSpec.Builder builder) {
        List<Element> responseElements = actionClass.getAnnotatedElements(com.santarest.annotations.Response.class);

        for (Element element : responseElements) {
            int status = element.getAnnotation(com.santarest.annotations.Response.class).value();
            if (status > 0) {
                builder.beginControlFlow("if(response.getStatus() == $L)", status);
                addResponseStatements(actionClass, builder, element);
                builder.endControlFlow();
            } else {
                addResponseStatements(actionClass, builder, element);
            }
        }
    }

    private void addResponseStatements(RestActionClass actionClass, MethodSpec.Builder builder, Element element) {
        String fieldAddress = getFieldAddress(actionClass, element);
        if (equalTypes(element, HttpBody.class)) {
            builder.addStatement(fieldAddress + " = response.getBody()", element);
        } else if (equalTypes(element, String.class)) {
            builder.addStatement(fieldAddress + " = response.getBody().toString()", element);
        } else {
            builder.addStatement(fieldAddress + " = ($T) converter.fromBody(response.getBody(), new $T<$T>(){}.getType())", element, element.asType(), TypeToken.class, element.asType());
        }
    }

    private void addBasicHeadersMap(RestActionClass actionClass, MethodSpec.Builder builder) {
        if (actionClass.getAnnotatedElements(ResponseHeader.class).isEmpty()) {
            return;
        }
        builder.addStatement("$T<$T, $T> $L = new $T<$T, $T>()", HashMap.class, String.class, String.class, BASE_HEADERS_MAP, HashMap.class, String.class, String.class);
        builder.beginControlFlow("for ($T header : response.getHeaders())", Header.class);
        builder.addStatement("$L.put(header.getName(), header.getValue())", BASE_HEADERS_MAP);
        builder.endControlFlow();
    }

    private void addResponseHeaders(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(ResponseHeader.class)) {
            ResponseHeader annotation = element.getAnnotation(ResponseHeader.class);
            String fieldAddress = getFieldAddress(actionClass, element);
            builder.addStatement(fieldAddress + " = $L.get($S)", element.toString(), BASE_HEADERS_MAP, annotation.value());
        }
    }

    private void addStatusField(RestActionClass actionClass, MethodSpec.Builder builder) {
        for (Element element : actionClass.getAnnotatedElements(Status.class)) {
            String fieldAddress = getFieldAddress(actionClass, element);
            if (TypeUtils.containsType(element, Boolean.class, boolean.class)) {
                builder.addStatement(fieldAddress + " = response.isSuccessful()", element);
            } else if (TypeUtils.containsType(element, Integer.class, int.class, long.class)) {
                builder.addStatement(fieldAddress + " = ($T) response.getStatus()", element, element.asType());
            } else if (equalTypes(element, String.class)) {
                builder.addStatement(fieldAddress + " = Integer.toString(response.getStatus())", element);
            } else if (TypeUtils.containsType(element, Long.class)) {
                builder.addStatement(fieldAddress + " = (long) response.getStatus()", element);
            }
        }
    }

    private static String getFieldAddress(RestActionClass actionClass, Element element) {
        String address;
        if (actionClass.getTypeElement().equals(element.getEnclosingElement())) {
            address = "action.$L";
        } else {
            address = String.format("((%s)action).$L", element.getEnclosingElement());
        }
        return address;
    }

}